"""Generate a Baseline/Optimized script pair, in their own folder, ready for
run_ab_test.py to run back to back -- or for manual PolyScope use, no live
send.py connection needed at all if you'd rather load them by hand.

    python export_manual_scripts.py --agent models/agent_ppo_movej.zip \\
        --recording data/ur5e/T08_slow_r1.csv --model models/distill-ur5e-v2.pkl \\
        --robot UR5e --out-dir manual_scripts --style movej

Writes ``<out-dir>/<name>/Baseline.script`` and ``<out-dir>/<name>/Optimized.script``.

Two styles:
  movej (default)   one movej(POSE, a=.., v=..) per move, same plain style as
                     scripts/*.script, each move using PPO's own (vel, acc)
                     literal -- readable, directly comparable to the original,
                     and runs through send.py's reliable wrap_program path
                     (the same one every plain --script test has succeeded on
                     today). The original script used one shared vel/acc for
                     every move; this uses a different pair *per* move since
                     that's what the policy actually chose.
  servoj             the exact PPO trajectory shape, as a compiled setpoint
                     stream -- what movej(vel, acc) actually produces once run
                     through the trapezoid math. Faithful to the finer shape,
                     but runs through the servoj-streaming path that's been
                     unreliable, and doesn't read like a hand-written script.
"""
from __future__ import annotations

import argparse
import os

import numpy as np
from stable_baselines3 import PPO

from analysis import Recording
from common import segments
from export_ppo_path import export_path
from send import wrap_path
from train_distillation_model import DistillModel
from train_ppo import _Move, obs_of, unmap_action
from utils import DT, Robot


def baseline_path(rec: Recording, robot: Robot, move: int | None = None) -> np.ndarray:
    """The recording's own commanded trajectory, move by move -- what
    export_path builds candidates from, unmodified, so the two paths are
    directly comparable (same moves, same order, only the speed differs)."""
    segs = [s for s in segments(rec) if s.i1 - s.i0 >= 3]
    if move is not None:
        segs = [segs[move]]
    return np.vstack([_Move(rec, s, robot).baseline_q for s in segs])


def movej_script(moves, segs, robot: Robot, mode: str, agent: PPO = None) -> str:
    """One ``movej(POSE, a=.., v=..)`` per move, PolyScope-readable.

    ``mode``:
      "recorded"  the move's *actual recorded* vel/acc (``segs[i].vel``/``.acc``,
                  read straight off the ``vel_cmd``/``acc_cmd`` RTDE registers
                  logged for that move -- not reconstructed/estimated).
      "ppo"       ``agent``'s own ``(vel, acc)`` per move (deterministic policy)
                  -- trades speed against staying near the recorded accuracy,
                  not pure maximum speed.
      "max"       the robot's real physical ceiling (``Robot.v_joint``/
                  ``a_joint``, uniform for every move) -- the controller clamps
                  anything above the true per-joint/Cartesian limit anyway (see
                  scripts/*.script's own comment on this), so this is "fastest
                  physically possible," not a PPO decision at all.

    Either way, this is a different (vel, acc) *per move*; the original
    script's one-shared-vel/acc isn't reconstructable from a single recording,
    which only ever ran at one speed.
    """
    label = {"recorded": "recorded", "ppo": "PPO-chosen", "max": "physical max"}[mode]
    lines = ["# Generated by export_manual_scripts.py -- one movej per recorded move.",
            f"# {label} (vel, acc) per move; not a shared vel/acc like the "
            "hand-written original.", ""]
    poses = [moves[0].q0] + [m.q1 for m in moves]
    for i, pose in enumerate(poses):
        lines.append(f"POSE_{i} = [{', '.join(f'{v:.6f}' for v in pose)}]")
    lines.append("")
    max_vel, max_acc = float(robot.v_joint.max()), float(robot.a_joint.max())
    for i, (m, s) in enumerate(zip(moves, segs)):
        if mode == "ppo":
            action, _ = agent.predict(obs_of(m), deterministic=True)
            vel, acc = unmap_action(action)
        elif mode == "max":
            vel, acc = max_vel, max_acc
        else:
            vel, acc = s.vel, s.acc
        lines.append(f"movej(POSE_{i + 1}, a={acc:.4f}, v={vel:.4f})")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(
        description="Export baseline + PPO-optimized .script files for manual PolyScope use.")
    ap.add_argument("--agent", default="models/agent_ppo_movej.zip", help="trained PPO agent")
    ap.add_argument("--recording", required=True, help="a data/ur5e/*.csv recording")
    ap.add_argument("--model", default="models/distill-ur5e-v2.pkl", help="distilled model pickle")
    ap.add_argument("--robot", default="UR5e", choices=list(Robot.MODELS))
    ap.add_argument("--move", type=int, default=None,
                    help="only this 0-indexed move, not the whole recording")
    ap.add_argument("--style", choices=("movej", "servoj"), default="movej",
                    help="movej (default): readable, one movej per move, runs "
                         "through send.py's reliable script path. servoj: exact "
                         "trajectory replay (see module docstring)")
    ap.add_argument("--max-speed", action="store_true",
                    help="also write MaxSpeed.script: every move at the robot's "
                         "real physical vel/acc ceiling, not a PPO decision "
                         "(movej style only)")
    ap.add_argument("--out-dir", default="manual_scripts", help="folder to write into")
    args = ap.parse_args()

    agent = PPO.load(args.agent, device="cpu")
    model = DistillModel.load(args.model)
    for p in model.parameters():
        p.requires_grad_(False)
    robot = Robot(args.robot)
    rec = Recording(args.recording)

    name = os.path.splitext(os.path.basename(args.recording))[0]
    if args.move is not None:
        name += f"_move{args.move}"
    pair_dir = os.path.join(args.out_dir, name)
    os.makedirs(pair_dir, exist_ok=True)
    base_out = os.path.join(pair_dir, "Baseline.script")
    opt_out = os.path.join(pair_dir, "Optimized.script")

    if args.style == "servoj":
        q_base = baseline_path(rec, robot, args.move)
        q_ppo = export_path(agent, model, robot, rec, args.move)
        for out, q in ((base_out, q_base), (opt_out, q_ppo)):
            with open(out, "w") as f:
                f.write(wrap_path([list(r) for r in q], DT))
            print(f"wrote {out}  ({len(q)} rows, {len(q) * DT:.2f} s)")
    else:
        segs = [s for s in segments(rec) if s.i1 - s.i0 >= 3]
        if args.move is not None:
            segs = [segs[args.move]]
        moves = [_Move(rec, s, robot) for s in segs]
        outputs = [(base_out, "recorded", None), (opt_out, "ppo", agent)]
        if args.max_speed:
            outputs.append((os.path.join(pair_dir, "MaxSpeed.script"), "max", None))
        for out, mode, agent_arg in outputs:
            with open(out, "w") as f:
                f.write(movej_script(moves, segs, robot, mode, agent_arg))
            print(f"wrote {out}  ({len(moves)} moves)")

    print(f"\n{pair_dir}/ ready. Run both back to back with:\n"
         f"  python run_ab_test.py --folder {pair_dir} --robot-ip <ip>\n"
         f"or load each .script onto the pendant (USB/network share) and run manually.")


if __name__ == "__main__":
    main()
